function [specification, popCounter, connCounter] = Benita_cortex_pyramidal_twoCompartment_model(specification, popCounter, connCounter)
% Setting up cortex pyramidal cell two compartment model
% Soplata implementation of cortex interneuron model as in:
%     - Benita, J. M., Guillamon, A., Deco, G., & Sanchez-Vives, M. V. (2012).
%     Synaptic ession and slow oscillatory activity in a biophysical
%     network model of the cerebral cortex. Frontiers in Computational
%     Neuroscience, 6. https://doi.org/10.3389/fncom.2012.00064

% Reference for meachnisms and implimentation of the model: 
% https://github.com/asoplata/dynasim-extended-benita-model

%% setting up dendrite of cortical cell
cortical_eqns = {...
    'dv/dt=(@current)/Cm';...
    'Cm = 1';...    % uF/cm^2
    'spike_threshold = -25';...
    'monitor v.spikes(spike_threshold, 1)';...
    'v(0) = -90'};
popCounter = popCounter + 1;
specification.populations(popCounter).name = 'PyCdr';
specification.populations(popCounter).size = 1;
specification.populations(popCounter).equations = cortical_eqns;
specification.populations(popCounter).mechanism_list = {...  
    'CaBuffer_PYdr_JB12',...
    'iHVA_PYdr_JB12',...
    'iKCa_PYdr_JB12',...
    'iNaP_PYdr_JB12',...
    'iAR_PYdr_JB12',...
    };

%% setting up soma of cortical cell
popCounter = popCounter + 1;
specification.populations(popCounter).name = 'PyCso';
specification.populations(popCounter).size = 1;
specification.populations(popCounter).equations = cortical_eqns;
specification.populations(popCounter).mechanism_list = {...  
    'iLeak_PYso_JB12',...
    'iNa_PYso_JB12',...
    'iK_PYso_JB12',...
    'iA_PYso_JB12',...
    'iKS_PYso_JB12',...
    };

%% setting up connect between soma and dendrite of cortical cell
connCounter = connCounter + 1;
specification.connections(connCounter).direction = 'PyCso<-PyCdr';
specification.connections(connCounter).mechanism_list={...
    'iCOM_PYso_PYdr_JB12',...
    'iNaCurrs_PYso_PYdr_JB12',...
    };
connCounter = connCounter + 1;
specification.connections(2).direction='PyCdr<-PyCso';
specification.connections(2).mechanism_list={...
    'iCOM_PYdr_PYso_JB12',...
    'iAMPA_PYdr_PYso_JB12',...
    'iNMDA_PYdr_PYso_JB12'};

end