function [specification, popCounter, connCounter] = Benita_cortex_interneuron_model(specification, popCounter, connCounter)
% Soplata implementation of cortex single compartment interneuron model as in:
%     - Benita, J. M., Guillamon, A., Deco, G., & Sanchez-Vives, M. V. (2012).
%     Synaptic ession and slow oscillatory activity in a biophysical
%     network model of the cerebral cortex. Frontiers in Computational
%     Neuroscience, 6. https://doi.org/10.3389/fncom.2012.00064

%% Setting up model for cortical interneuron 
popCounter = popCounter + 1;
specification.populations(popCounter).name = 'IN';
specification.populations(popCounter).size = 1;
specification.populations(popCounter).equations = {...
    'dV/dt = (@current)./Cm';...
%     'HyperP(t) = 0*(t < 400) - 1*(t > 400 && t < 600) + 0*(t > 600)';...
%     'Iapp(t) =  0*(t < 200) + 10*(t > 200 && t < 800)';...
    'Cm = 1';...    % uF/cm^2
    'spike_threshold = -5';...
    'monitor V.spikes(spike_threshold, 1)';...
    'V(0) = -65'};
specification.populations(popCounter).mechanism_list = {...
    'iLeak_IN_JB12',...
    'iNa_IN_JB12',...
    'iK_IN_JB12',...
    };
end